version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: ~/thisitem
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: 
          name: start listen server
          command:
            go run hello.go
      - run:
          name: test hello.go
          command:
            curl 127.0.0.1:8800
  deployToTest:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: ~/thisitem
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: 
          name:  build docker image
          command:
            docker build -t myimage.xxx.com/hello:v1 .
      - run:
          name: push your image
          command:
            echo "docker push imagename"            
      
