version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: ~/thisitem
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: 
          name: start hello server
          command:
            go build hello.go 
            ./hello &
      - run:
          name: test hello.go
          command:
            echo "test hello.go"
  deployToTest:
    docker:
      # specify the version
      - image: circleci/golang:1.9
    working_directory: ~/thisitem
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: 
          name:  build docker image
          command:
            docker build -t myimage.xxx.com/hello:v1 .
      - run:
          name: push your image
          command:
            echo "docker push imagename"            
workflows:
  version: 2
  authDeploy:
    jobs:
      - build
      - deployToTest:
          requires:
            - build    
